name = "framevideos-api"
main = "src/index.ts"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

[triggers]
crons = ["*/5 * * * *"]

# D1
[[d1_databases]]
binding = "DB"
database_name = "frame-videos-db"
database_id = "dae9bd51-c863-42b0-b5b6-21f4569aa6c9"

# R2
[[r2_buckets]]
binding = "STORAGE"
bucket_name = "frame-videos-storage"

# KV
[[kv_namespaces]]
binding = "CACHE"
id = "6be904ed61714310b45e04f7c181f1ba"

[vars]
ENVIRONMENT = "development"

[env.staging]
name = "framevideos-api-staging"
[env.staging.vars]
ENVIRONMENT = "staging"

[[env.staging.d1_databases]]
binding = "DB"
database_name = "frame-videos-db"
database_id = "dae9bd51-c863-42b0-b5b6-21f4569aa6c9"

[[env.staging.r2_buckets]]
binding = "STORAGE"
bucket_name = "frame-videos-storage"

[[env.staging.kv_namespaces]]
binding = "CACHE"
id = "6be904ed61714310b45e04f7c181f1ba"

[env.production]
name = "framevideos-api"
routes = [{ pattern = "api.framevideos.com/*", zone_name = "framevideos.com" }]
[env.production.vars]
ENVIRONMENT = "production"

[[env.production.d1_databases]]
binding = "DB"
database_name = "frame-videos-db"
database_id = "dae9bd51-c863-42b0-b5b6-21f4569aa6c9"

[[env.production.r2_buckets]]
binding = "STORAGE"
bucket_name = "frame-videos-storage"

[[env.production.kv_namespaces]]
binding = "CACHE"
id = "6be904ed61714310b45e04f7c181f1ba"
